version: '3'
services:
  master:
    restart: unless-stopped
    build: ./jenkins
    ports:
      - "50000:50000"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net
  nginx:
    restart: unless-stopped
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - jenkins-net
    depends_on:
      - master
volumes:
  jenkins-data:
  jenkins-log:
networks:
  jenkins-net: